### ISSUE TITLE
gh-screensaver/bin/cmd.out: No such file or directory

### ISSUE THREAD

**Issue by andypiper** [vilmibm/gh-screensaver#14]
Likely to be the same problem as [this](https://github.com/vilmibm/gh-user-status/issues/2) and [this](https://github.com/vilmibm/gh-contribute/issues/8). Reporting for completeness across the 3 extensions I've been using - NB they previously work / worked on my Intel MBP, this is on an M1 Pro model.

Running `gh-screensaver` results in the error:

`/Users/andypiper/.local/share/gh/extensions/gh-screensaver/gh-screensaver: line 54: /Users/andypiper/.local/share/gh/extensions/gh-screensaver/bin/cmd.out: No such file or directory`

```
$ ls /Users/andypiper/.local/share/gh/extensions/gh-screensaver
LICENSE        cmd.out        go.mod         main.go        savers
README.md      gh-screensaver go.sum         release.sh     util.go
```

**Comment by vilmibm** [comment]
please reopen if this keeps happening with v2.0.1
