### ISSUE TITLE
Broken argument handling in marquee screensaver

### ISSUE THREAD

**Issue by ewe2** [vilmibm/gh-screensaver#4]
1 . Error encountered:
When attempting to use the example marquee options --message and/or --font, they fail with the error "unknown flag" and the option attempted.

2. Steps to reproduce:
Run the example `gh screensaver -smarquee --message="hello world" --font="script"`

**Comment by vilmibm** [comment]
ah sorry, you need to put `--` before any screensaver specific arguments, like so:

```bash
gh screensaver -smarquee -- --message="hello world" --font="script"
```

Are there bad docs somewhere?

**Comment by ewe2** [comment]
Just the example in the screensaver help text which is also a bit misspelt! It's correct in README.md but users may not catch that.

**Comment by vilmibm** [comment]
oops :( fixed, thanks!
